[build]
# نختار بايثون 3.10 بشكل صريح
nixpkgs = ["python310", "gcc"]

[phases.setup]
commands = [
  "echo using python",
  "python3.10 --version"
]

[phases.install]
commands = [
  "python3.10 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[phases.build]
commands = [
  "python3.10 -m pip install -r requirements.txt"
]

[start]
cmd = "gunicorn palm_diagnosis.wsgi --timeout 200"
